### ISSUE TITLE
What's the best way to incorporate this into a package?

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaLang/PackageCompiler.jl#10]
So that compilation is more complete without the user having to do anything. Is it to include in the the Package.jl file under src?

**Comment by SimonDanisch** [comment]
Since it's basically a build step, I included PackageCompiler into Pkg.build("Package") step via the "deps/build.jl" file. 
Sadly the user will always need to interact, since you shouldn't just overwrite the users system image without making it explicit, and if you don't force it the user needs to make sure to load the custom system image.
I offered those choices via an environment variable.

**Comment by diegozea** [comment]
Are you talking about https://github.com/JuliaPlots/Makie.jl/blob/master/deps/build.jl ?

What would happen if two different packages did this? Would the second package delete the compiled image of the first?

**Comment by SimonDanisch** [comment]
That's why I removed the compile command from the Makie build, and instead started offering compiling multiple packages: `compile_package(packages...)`...
I guess there is not much one can do right now in isolation for a package, besides compiling a shared library/executable or a self contained system image...

**Comment by diegozea** [comment]
Do you know if the new package manager could help to have compiled packages?

**Comment by SimonDanisch** [comment]
That isn't really about the package manager... It's more about seperating out binaries for each module/package, which seems to be a tricky topic. Once that's figured out, we can integrate into all sorts of things, e.g. the package manager ;)
