### ISSUE TITLE
Way to specify target architecture for compile_package?

### ISSUE THREAD

**Issue by JackDunnNZ** [JuliaLang/PackageCompiler.jl#118]
I would like to generate a compiled sysimg for a wider target architecture than the default choice. Currently I have modified `compile_package` [here](https://github.com/JuliaLang/PackageCompiler.jl/blob/d7726d2386437ec38bc8aa05fa8a01cd00406b44/src/PackageCompiler.jl#L136) to pass the desired `cpu_target`, but it would be good to have this supported in the main package. 

I would file a PR but I am not sure which flags you would think to expose or the best way to organize it.

**Comment by NHDaly** [comment]
There's already a flag for it! :)

I think on juliac it's `-C`, and in the Julia function, static_julia, it's `cpu_target`.

I'm on vacation now but I'll check in a bit. For example, though, when compiling on a Mac, I use `-C x86-64` to target all Macs.

**Comment by JackDunnNZ** [comment]
Thanks for the response, no rush at all!

The problem I'm having is simply that the `cpu_target` is not used in the call to `build_sysimg` inside the `compile_package` function (which is my entry point to the package). `build_sysimg` is just a wrapper around `static_julia` and even has the `cpu_target` arg, but it's just not used at the call site.

For clarity, my workflow is simply

```julia
using PackageCompiler
compile_package("xxx")
```

and it would be great to be able to have

```julia
using PackageCompiler
compile_package("xxx", cpu_target="x86-64")
```

**Comment by NHDaly** [comment]
Ah yes makes sense! I think that sounds great, I'd say just sending a PR to add that option makes sense!

Just curious, can you elaborate on your use-case? Why are you hoping to build a sysimg for a larger target? Is this for a sysadmin type situation where you want to share your precompiled sysimg with people?

Because you should know, we're still experimenting to figure out how this all works best ([here](https://github.com/JuliaLang/PackageCompiler.jl/issues/110) and [here](https://github.com/NHDaly/ApplicationBuilder.jl/issues/24) at least), but I think that if you start julia using a sysimg built for a more generic target, it's by default going to recompile everything for `native` anyway!

So if you _do_ build a sysimg for a non-`native` cpu target, when you use it, you should start julia with either `--compile=min` or `--compile=no`. :) That could be part of why Simon didn't add the option to specify a cpu_target on `compile_package`: it's currently intended as basically a way to speed-up julia on your own machine.

So hearing more about your intended use would help figure out how to change the api! :)

**Comment by SimonDanisch** [comment]
Yeah I guess I was imagining `compile_package("xxx")` as something you would use locally. We haven't really figured out an API to ship compiled images, so it hasn't really been part of the prime use cases ;)

**Comment by JackDunnNZ** [comment]
Thanks that's really helpful. Yeah, right now we are just using it as a mechanism for building and shipping a batteries-included sysimg (with some unregistered and/or private packages) just so that we can get people up and running as fast as possible without having to worry about getting them access to repos etc- the compilation speed up is not really on the radar but would be a nice-to-have!

I'll file the PR, but I don't want to get in the way of your design - I think we are a pretty edge case and I am happy to work around things. I think the "proper" end game would be for us to move to a compiled library instead (where things like #26 look really cool), but right now it's good just to have something easy (albeit hacky) that works!

**Comment by SimonDanisch** [comment]
I don't think exposing the cpu target flag will be any problem to our design ;) It's just I didn't expect it..
