### ISSUE TITLE
Issue compiling HTTP.jl

### ISSUE THREAD

**Issue by topspin89** [JuliaLang/PackageCompiler.jl#148]
Trying to compile HTTP.jl gives the following error:

fatal: error thrown and no exception handler available.
ErrorException("Task cannot be serialized")
rec_backtrace at /buildworker/worker/package_linux64/build/src/stackwalk.c:94
record_backtrace at /buildworker/worker/package_linux64/build/src/task.c:246
jl_throw at /buildworker/worker/package_linux64/build/src/task.c:577
jl_error at /buildworker/worker/package_linux64/build/src/rtutils.c:41
jl_serialize_value_ at /buildworker/worker/package_linux64/build/src/staticdata.c:293
jl_serialize_value_ at /buildworker/worker/package_linux64/build/src/staticdata.c:285
jl_serialize_value_ at /buildworker/worker/package_linux64/build/src/julia.h:894 [inlined]...

I can fix it by removing option '--output-o $o_file'

**Comment by SimonDanisch** [comment]
There is likely a task somewhere in global scope!

**Comment by topspin89** [comment]
What can i do now? if i removing '--output-o $o_file', i can't get compiled files.

**Comment by SimonDanisch** [comment]
Look for global variables in HTTP (search for `global` / `const`)  and initialize them in `__init__` instead of having them sit in global scope...E.g.:

```Julia
const http_global = Dict(:a => rand(100))
```
Would become:
```Julia
const http_global = Ref{Dict}()
function __init__()
    http_global[] = Dict(:a => rand(100))
end
```
Or something like that ;) 
Relatively sure, that by removing '--output-o $o_file', you simply don't statically compile anymore!
You can also raise this issue at the Julia repository and plead to improve static compilation for globals!

**Comment by NHDaly** [comment]
If you build with `ApplicationBuilder`, we set an environment variable to let you know whether your code is being compiled statically or not, so in the presence of that environment variable you can do the code Simon suggested above.

Here's an example:
https://github.com/NHDaly/ApplicationBuilder.jl/blob/master/examples/sdl.jl#L18-L24

For your example that would be something like this:
```julia
if get(ENV, "COMPILING_APPLE_BUNDLE", "false") == "true"
    const http_global = Ref{Dict}()
    function __init__()
        http_global[] = Dict(:a => rand(100))
    end
end
```

That said, I think ApplicationBuilder is a bit out of date, since i haven't been focusing on it recently... I'll try to put some attention back on that soon!

**Comment by topspin89** [comment]
Thanks! it's worked!

**Comment by christopher-dG** [comment]
Sorry to resurrect this, but @topspin89 have you successfully compiled HTTP.jl? I can't get around the "Task cannot be serialized" error.

**Comment by topspin89** [comment]
@christopher-dG, hello! Yep, i compiled http.jl, I created fork for this and change initialize of global variable

**Comment by SimonDanisch** [comment]
can you make a PR to http.jl and post it here? :)

**Comment by christopher-dG** [comment]
I tried applying the same changes so that I could make the PR but I still got the same error when compiling. I also got the error on @topspin89's fork.
There are indeed a lot of global/const variables in HTTP. I don't really have time to try to fix it right now but I'll dig into it in the future, since compiling HTTP would help me a lot.
