### ISSUE TITLE
Extremely long loading time

### ISSUE THREAD

**Issue by Petr-Hlavenka** [JuliaLang/PackageCompiler.jl#164]
I've been using PackageCompiler quite heavily in julia 1.0.1 on Win7. and the package seemed to me to load imediatelly. Now on Win10 + julia 1.0.3 have to wait > 2 minutes after `using PackageCompiller`. Do others also experience the same? Do you know what it causes?

**Comment by cbtek** [comment]
This is my first time using Julia (64-bit, version 1.03 on Windows) and I'm experiencing waits exceeding 2 minutes as well.    I was simply testing the build_shared_lib feature with a function that multiplies and returns two numbers.  Is it normal for PackageCompiler to generate a DLL in excess of 100MB for such a simple function?

**Comment by phlavenk** [comment]
The large size of compiled binary DLL is normal. What's inside your DLL is the full binary image of all the functions defined in Core., Base., Stdlibs, and all packages you depend on, just for the case these functions might be called from the little of your code. There is the "minimalist static" compilation down the roadmap, but the manpower is now focused to areas that bother the important "customers" most -  ML+GPU, HPC. Embedding use-case (aka use binaries on computer without julia install) is quite low now.

On the other hand, the usage slowness of PackageCompiler should be addressed as a clear regression case. Might be maybe worth filling an issue in Julia as this is most probably caused by changes there.

**Comment by SimonDanisch** [comment]
Just started using PackageCompiler on Windows... The issue seems to be with WinRPM!

**Comment by phlavenk** [comment]
Simon, do you know of any attempts to move gcc into BinaryBuilder framework and get rid of WinRPM?
