### ISSUE TITLE
binary built with PackageCompiler v0.6.5 runs faster than v1.0.2?

### ISSUE THREAD

**Issue by ChelseaTrotter** [JuliaLang/PackageCompiler.jl#364]
Hello, 

I've been experimenting with PackageCompiler to build a binary for my application. However the binary built by v1.0.2 is significantly slower than previous version v0.6.5. So I tested it out with the example file MyApp.jl, and I got similar issue. 
With v1.0.2, MyApp runs about 5.7 seconds,
With v0.6.5, MyApp runs about 1.2 seconds. 

Why is it?

I used the following code to build the binary for MyApp.jl with v1.0.2 and run it, then build it with v0.6.5 and time it too. 
```julia

using Pkg
# Setting PackageCompiler to version 1.0.2
Pkg.pin(PackageSpec(name="PackageCompiler", version="1.0.2"))
# double checking package Directory. And later on will use different PackageCompiler versions to compile the same code. 
pkg_compile_dir = Pkg.API.dir("PackageCompiler")

using PackageCompiler
app_dir = joinpath(pkg_compile_dir,"examples", "MyApp")
bin_dir = joinpath(pkg_compile_dir,"examples", "MyAppCompiled")
create_app(app_dir, bin_dir, force=true)

v1_bin = joinpath(bin_dir, "bin", "MyApp")
@time run(`$v1_bin`)

#################################
# just modifying the source code to accommodate V0.6.5
src_file = joinpath(app_dir, "src", "MyApp.jl")
Base.Filesystem.chmod(src_file, 0o666)

f = open(src_file)
lines = readlines(f);
close(f)

# checking of file is modified by me.
for i in 1:length(lines)
    if (occursin("julia_main()",lines[i]))
        lines[i] = "Base.@ccallable function julia_main(ARGS::Vector{String})::Cint"
        break
    end
end


open(src_file, "w") do f
   for i in 1:length(lines)
      write(f, "$(lines[i]) \n")
   end
end
#################################

Pkg.pin(PackageSpec(name="PackageCompiler", version="0.6.5"))
Pkg.status("PackageCompiler")
using PackageCompiler
build_dir = joinpath(app_dir, "..", "builddir")
build_executable(src_file, builddir = build_dir)

v0_bin = joinpath(build_dir, "MyApp")
@time run(`$v0_bin`)

```

**Comment by KristofferC** [comment]
Short version: passing `incremental=true` to `create_app` should "fix" it or, even better, use the `precompile_execution_file="examples/MyApp/precompile_app.jl"`.

Longer version: By default, PackageCompiler uses `incremental=false` (see https://julialang.github.io/PackageCompiler.jl/dev/apps/#Incremental-vs-non-incremental-sysimage-1). This means that a brand new sysimage is built instead of additively putting things on top of the default sysimage. The default sysimage contains a lot of stuff that we don't need in an App (it has a lot of code to make the REPL start quickly for example). Therefore it is better to start form scratch and only compile the things that we need for the app by using the `precompile_execution_file` argument. The old behavior of PackageCompiler was to use the previous sysimage as the base, which can be recreated in new PackageCompiler with `incremental=true`.

**Comment by ChelseaTrotter** [comment]
Thank you! It does make a big difference. I think it makes sense to make `incremental=false` the default because majority of the Julia image may not be used by the new app. But I don't quite understand why when `incremental=true` produces a faster binary, it is a little counterintuitive. 

Passing a `precompile_app.jl` does the trick. I think this argument should be required, because that would be what I expect the default behavior of `create_app`

Many thanks!

**Comment by KristofferC** [comment]
At least a warning might make sense
