### ISSUE TITLE
macOS: "Julia-1.4.app" is damaged and can't be opened. You should move it to the trash.

### ISSUE THREAD

**Issue by MFairley** [JuliaLang/PackageCompiler.jl#409]
I keep running into this dialogue box. It happened most recently after restarting my computer and opening up VSCode, which opens up a Julia session. I'm using macOS 10.15.4.

<img width="420" alt="Screen Shot 2020-05-06 at 2 11 14 PM" src="https://user-images.githubusercontent.com/4374785/81218459-d6898780-8fa3-11ea-954c-940147cf8927.png">

**Comment by jakobnissen** [comment]
I've just run into this issue with Julia 1.5.0 beta, and I have NOT used PackageCompiler. Furthermore, the binary executable has not been modified since its installation.

**Comment by vp2177** [comment]
^Same here, but with Julia 1.4.2. Have also not used PackageCompiler (unless the VSCode plugin uses it under the hood).

**Comment by chelseas** [comment]
Ok so can someone give really specific instructions about how to get around this error?

How do I tell PackageCompiler.jl to create the new system image and store it in a place so that it _doesn't_ replace the original system image?

And once I've done this, how do I use Julia with either the o.g. system image (should be unchanged, right?) and how do I use Julia with the new system image created from PackageCompiler.jl?

system specs lite:
mac user (catalina)
package compiler user

**Comment by KristofferC** [comment]
It shouldn't replace the default sysimage unless you actively tell it not to. Are you sure the default sysimage is changed? Is there some other file that is being modified / added?

**Comment by chelseas** [comment]
How do I use the system image created by package compiler without replacing the default system image? I don't see an example in the docs.

**Comment by toollu** [comment]
Same here, Julia 1.5 with 10.15.4. Documentation/ workaround would be appreciated.

**Comment by pfitzseb** [comment]
As per the [Julia docs](https://docs.julialang.org/en/latest/manual/getting-started/) (or `julia --help`): You can use the `-J`/`--sysimage` flags to specify what system image Julia should use.

**Comment by toollu** [comment]
The -J option does not help if the default sys image is affected...

**Comment by KristofferC** [comment]
The `replace_default` option is now discouraged and will likely be removed so closing this.
