### ISSUE TITLE
Blosc library loading error.

### ISSUE THREAD

**Issue by alvitg** [JuliaLang/PackageCompiler.jl#86]
I am trying to make portable Win x64 binary using package compiler. Julia source itself uses the following libraries:

```julia
using StrPack
using DataFrames
using CSV
using MAT
using ArgParse
```
Compilation looks like this:
```julia
build_executable("navconvert.jl"; builddir="win", cpu_target="x86-64")
```

Resulting executable works on the machine it was compiled on.

After movement of the whole "win" directory to a computer where Julia is not installed, I obtain the following error:
```log
fatal: error thrown and no exception handler available.
Base.InitError(mod=:Blosc, error=ErrorException("C:\Users\user\.julia\v0.6\Blosc\src\..\deps\usr\bin\libblosc.dll does not exist, Please re-run Pkg.build("Blosc"), and restart Julia."))
```

It is clear that libblosc.dll is not moved to the build directory at compilation stage, but manual addition of the library to the mentioned directory does not change anything.

The same behavior is observed on Mac OS 10.13 with libblosc.1.14.3.dylib.

Conclusion: it seems that full runtime path to the dll is hardcoded into the built executable.

Julia version 0.6.3, PackageCompiler version from June 17, 2018.

**Comment by SimonDanisch** [comment]
Yeah, this is quite unfortunate. Right now, 90% of packages with binary dependencies have their path hardcoded. We'll need to coordinate this with Pkg3 + BinaryProvider.
We have roughly three options: 

* use only the name of the library in the ccalls, and make sure that it's in the path after deploy. So packagecompiler would need to have a list of binaries it needs to put in the path. This is a pretty dirty solution and likely not prefered, but could be quickly tested ;) 

* make the deps.jl file generated by BinaryProvider dynamic so that BinaryProvider + PackageCompiler can cooperate and move the dependencies to a location that can be rediscovered by the deps file after deploy

* have Pkg3 know about PackageCompiler and have a setup script that installs all binary dependencies after deploy (will need something like the previous point - but will avoid shipping all depending binaries with the julia binary)

CC: @Keno, @staticfloat , @KristofferC

**Comment by DilumAluthge** [comment]
@SimonDanisch Any update on this?

**Comment by NHDaly** [comment]
So I've been working on this problem here: https://github.com/NHDaly/ApplicationBuilder.jl

I'm giving a talk this week at JuliaCon about compiling binaries and bundling them with all the packages + binary dependencies your code needs!! :)

The current solution requires you to manually override the hard-coded paths in your julia project, but i'm hoping this can be automated away. It's something I plan to talk to people about at JuliaCon, actually!
Here's an example:
https://github.com/NHDaly/ApplicationBuilder.jl/blob/88b63215f08e1d8509a2c8de5d43bde7a1ec5d5b/examples/sdl.jl#L17-L24
And here's it's associated build file:
https://github.com/NHDaly/ApplicationBuilder.jl/blob/88b63215f08e1d8509a2c8de5d43bde7a1ec5d5b/test/build_examples/sdl.jl


So, that example is mac-specific, but the process is realllly similar on Windows. 
You would just need to point ApplicationBuilder at your library: `"C:\Users\user\.julia\v0.6\Blosc\src\..\deps\usr\bin\libblosc.dll"`. And actually, it's easier, because on Windows you don't need to worry about all the `rpath` stuff in there.

**Comment by NHDaly** [comment]
But yeah, like @SimonDanisch said, the hardcoded paths is the main big problem remaining with this process.

Hopefully, coming out of this week, we'll have the beginnings of a solution.

**Comment by JackDunnNZ** [comment]
Is there any progress on this? Right now I am doing something like "use only the name of the library in the ccalls" by manually changing the file, but it would be nice to have a better solution :)

**Comment by KristofferC** [comment]
The solution is to use the artifact system / use `_jll` packages.
